SitioWeb/Models/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SitioWeb.Models
{
    public class Vehiculo
    {
        public int CantidadDisponible { get; set; } 
        public int CantidadPuertas { get; set; } 
        public int CiudadId { get; set; } 
        public int Id { get; set; } 
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public float PrecioPorDia { get; set; }
        public int Puntaje { get; set; }       
        public bool TieneAireAcon { get; set; }         
        public bool TieneDireccion { get; set; }
        public string TipoCambio { get; set; } 
        public int VehiculoCiudadId { get; set; }
        
        public double CalculoPrecioAlPublico()
        {
            return (double)(this.PrecioPorDia * 1.2);
        }

    }
}

SitioWeb/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SitioWeb.Models;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using SitioWeb;
using System.Text;


namespace SitioWeb.Controllers
{
    public class VehiculoController : Controller
    {
        string Baseurl = "http://localhost:61319/";

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Vehiculo/       
        public ActionResult Index(int? idPais, int? idCiudad)
        {
            try
            {
                if (idPais != null)
                {
                    //@ViewBag.paisSelec = idPais;
                    ViewBag.Pais = new SelectList(ConsultarPaises(), "Id", "Nombre", idPais);
                    if (idCiudad != null) { ViewBag.Ciudad = new SelectList(ConsultarCiudades(idPais), "Id", "Nombre", idCiudad); }
                    else { ViewBag.Ciudad = new SelectList(ConsultarCiudades(idPais), "Id", "Nombre"); }
                }
                else
                {
                    ViewBag.Pais = new SelectList(ConsultarPaises(), "Id", "Nombre");
                }
                if (idCiudad != null)
                {
                    List<Vehiculo> list = ConsultarVehiculos(idCiudad);
                    Session["vehiculos"] = list;
                    Session["idPais"] = idPais;
                    return View(list);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex) { return RedirectToAction("Error", "Home", new { mensaje = ex.Message }); }

        }

        public ActionResult Reservar(int Id)
        {
            try
            {
                ViewBag.Cliente = ConsultarCliente();
                ViewBag.Vendedor = ConsultarVendedor();
                List<Vehiculo> list = (List<Vehiculo>)Session["vehiculos"];
                Vehiculo vehiculo = list.Single(a => a.Id == Id);
                return View(vehiculo);
            }
            catch (Exception ex) { return RedirectToAction("Error", "Home", new { mensaje = ex.Message }); }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearReserva(FormCollection form)
        {
            try
            {
                List<Vehiculo> list = (List<Vehiculo>)Session["vehiculos"];
                Vehiculo vehiculo = list.Single(a => a.Id == Convert.ToInt32(form["Id"]));
                Reserva reserva = new Reserva
                {
                    IdCliente = Convert.ToInt32(form["Clientes"]),
                    IdVendedor = Convert.ToInt32(form["Vendedores"]),
                    IdVehiculoCiudad = vehiculo.VehiculoCiudadId,
                    FechaReserva = DateTime.Now.ToString(),
                    Costo = Convert.ToDecimal(vehiculo.PrecioPorDia),
                    FechaHoraDevolucion = form["FechaHoraDevolucion"],
                    FechaHoraRetiro = form["FechaHoraRetiro"],
                    LugarRetiro = form["LugarRetiro"],
                    LugarDevolucion = form["LugarDevolucion"],
                    PrecioVenta = Convert.ToDecimal(vehiculo.CalculoPrecioAlPublico()),
                    IdPais = (int)Session["idPais"],
                    IdCiudad = vehiculo.CiudadId,
                    Id = Convert.ToInt32(form["Id"]),
                };
                if (!GuardarReserva(reserva))
                {
                    //return RedirectToAction("Reservar", new { Id = Convert.ToInt32(form["Id"]) });
                    return View();
                }
                return RedirectToAction("Index", "Reserva"); ;
            }
            catch (Exception ex) { return RedirectToAction("Error", "Home", new { mensaje = ex.Message }); }
        }

        private Boolean GuardarReserva(Reserva reserva)
        {
            var jsonRequest = JsonConvert.SerializeObject(reserva);

            var httpContent = new StringContent(jsonRequest, Encoding.UTF8, "application/json");

            var cliente = new HttpClient()
            {
                BaseAddress = new Uri(Baseurl)
            };
            try
            {
                AccessToken token = (AccessToken)Session["token"];
                if (token == null)
                {
                    token = new AccessToken();
                    token.access_token = "noAutorizado";
                }
                var url = "api/Reservas/ReservarVehiculo/" + token.access_token;

                var res = cliente.PostAsync(url, httpContent).Result;

                if (!res.IsSuccessStatusCode)
                {
                    System.Web.Http.HttpError error = res.Content.ReadAsAsync<System.Web.Http.HttpError>().Result;
                    if (error != null)
                        throw new HttpRequestException("Código: " + (int)res.StatusCode + ". Descripción: " + res.ReasonPhrase + ". Detalle: " + error.ExceptionMessage);
                    else
                        throw new HttpRequestException("Código: " + (int)res.StatusCode + ". Descripción: " + res.ReasonPhrase);
                }
                return true;
            }
            catch (HttpRequestException hre) { throw hre; }
            catch (Exception ex) { throw ex; }
        }

        private List<Vendedor> ConsultarVendedor()
        {
            List<Vendedor> list = new List<Vendedor>();

            using (var client = new HttpClient())
            {
                try
                {
                    AccessToken token = (AccessToken)Session["token"];
                    if (token == null)
                    {
                        token = new AccessToken();
                        token.access_token = "noAutorizado";
                    }
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage Res = client.GetAsync("api/Vehiculos/Vendedor/" + token.access_token).Result;
                    if (Res.IsSuccessStatusCode)
                    {
                        var VendedorResponse = Res.Content.ReadAsStringAsync().Result;
                        list = JsonConvert.DeserializeObject<List<Vendedor>>((VendedorResponse));

                    }
                    else
                    {
                        System.Web.Http.HttpError error = Res.Content.ReadAsAsync<System.Web.Http.HttpError>().Result;
                        if (error != null)
                            throw new HttpRequestException("Código: " + (int)Res.StatusCode + ". Descripción: " + Res.ReasonPhrase + ". Detalle: " + error.ExceptionMessage);
                        else
                            throw new HttpRequestException("Código: " + (int)Res.StatusCode + ". Descripción: " + Res.ReasonPhrase);
                    }
                    return list;
                }
                catch (HttpRequestException hre) { throw hre; }
                catch (Exception ex) { throw ex; }
            }
        }

        private List<Cliente> ConsultarCliente()
        {
            List<Cliente> list = new List<Cliente>();

            using (var client = new HttpClient())
            {
                try
                {
                    AccessToken token = (AccessToken)Session["token"];
                    if (token == null)
                    {
                        token = new AccessToken();
                        token.access_token = "noAutorizado";
                    }
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage Res = client.GetAsync("api/Vehiculos/Cliente/" + token.access_token).Result;
                    if (Res.IsSuccessStatusCode)
                    {
                        var ClienteResponse = Res.Content.ReadAsStringAsync().Result;
                        list = JsonConvert.DeserializeObject<List<Cliente>>((ClienteResponse));

                    }
                    else
                    {
                        System.Web.Http.HttpError error = Res.Content.ReadAsAsync<System.Web.Http.HttpError>().Result;
                        if (error != null)
                            throw new HttpRequestException("Código: " + (int)Res.StatusCode + ". Descripción: " + Res.ReasonPhrase + ". Detalle: " + error.ExceptionMessage);
                        else
                            throw new HttpRequestException("Código: " + (int)Res.StatusCode + ". Descripción: " + Res.ReasonPhrase);
                    }
                    return list;
                }
                catch (HttpRequestException hre) { throw hre; }
                catch (Exception ex) { throw ex; }
            }
        }

        public List<Pais> ConsultarPaises()
        {
            List<Pais> list = new List<Pais>();
            using (var client = new HttpClient())
            {
                try
                {
                    AccessToken token = (AccessToken)Session["token"];
                    if (token == null)
                    {
                        token = new AccessToken();
                        token.access_token = "noAutorizado";
                    }
                    client.BaseAddress = new Uri(Baseurl);

SitioWeb/Views/Vehiculo/Index.cshtml
@model IEnumerable<SitioWeb.Models.Vehiculo>

@{
    ViewBag.Title = "Vehículos";
}

<h2>@ViewBag.Title</h2>
<div class="panel panel-default">
    <div class="panel-heading text-center><h2>Vehiculos</h2></div>

    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group row">
                <div class="col-xs-12 col-md-5">
                    @Html.DropDownList("Paises", (SelectList)ViewBag.Pais, "Seleccione pais", new { @class = "form-control", @onchange = "cargoCiudad(this)" })
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                    @if (ViewBag.Ciudad != null)
                    {

                        @Html.DropDownList("Ciudades", (SelectList)ViewBag.Ciudad, "Seleccione ciudad", new { @class = "form-control", @onchange = "cargoVehiculo(this)" })

                    }
            </div>
        </div>
        
        
    </div>
</div>

@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CantidadDisponible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadPuertas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CiudadId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioPorDia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TieneAireAcon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TieneDireccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoCambio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehiculoCiudadId)
            </th>
            <th>
                @Html.Label("Precio al publico")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadDisponible)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadPuertas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CiudadId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecioPorDia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Puntaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TieneAireAcon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TieneDireccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoCambio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehiculoCiudadId)
                </td>
                <td>
                    @Html.Label(item.CalculoPrecioAlPublico().ToString())
                </td>
                <td>

                    @Html.ActionLink("Reservar", "Reservar", new { Id = item.Id })

                </td>
            </tr>
        }

    </table>

}


<script>
    function cargoCiudad(item) {
        location.href = '@Url.Action("Index", "Vehiculo")?idPais=' + item.value;
        ;
    }
    function cargoVehiculo(item) {
        location.href = '@Url.Action("Index", "Vehiculo")?idPais=' + Paises.value + '&idCiudad=' + item.value;
        ;
    }
</script>

SitioWeb/Views/Vehiculo/Reservar.cshtml
@model SitioWeb.Models.Vehiculo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@using (Html.BeginForm("CrearReserva", "Vehiculo",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div>
        <h4>Vehiculo</h4>
        <hr />
        @Html.Hidden("Id", Model.Id, new { @class = "form-control" })
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CantidadDisponible)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.CantidadDisponible)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CantidadPuertas)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.CantidadPuertas)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CiudadId)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.CiudadId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Marca)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.Marca)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Modelo)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.Modelo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PrecioPorDia)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.PrecioPorDia)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Puntaje)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.Puntaje)
            </dd>

            <dt>
                @Html.Label("Aire acondicionado")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TieneAireAcon)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TieneDireccion)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.TieneDireccion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TipoCambio)
            </dt>

            <dd >
                    @Html.DisplayFor(model => model.TipoCambio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.VehiculoCiudadId)
            </dt>

            <dd >
                @Html.DisplayFor(model => model.VehiculoCiudadId)
            </dd>
                        <dt>
                            @Html.Label("Precio Al Publico")
                        </dt>

            <dd >
               
                    @{
                    var precio = Model.CalculoPrecioAlPublico();
                    @Html.Label("" + precio)
                    }
              
            </dd>

        </dl>
     </div>
    
        <div class="panel panel-default">
    <div class="panel-heading text-center><h2>Reserva</h2></div>

    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group row">
                <div class="col-xs-12 col-md-5">
                    @Html.DropDownList("Clientes", new SelectList(ViewBag.Cliente, "Id", "NroDocumento"), "Seleccione cliente", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                    @Html.DropDownList("Vendedores", new SelectList(ViewBag.Vendedor, "Id", "Nombre"), "Seleccione vendedor", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                Dia de Retiro:
                @Html.TextBox("FechaHoraRetiro", null, "Ingrese el día", new { @type = "date" }) 
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                Día de Devolucion:
                @Html.TextBox("FechaHoraDevolucion", null, "Ingrese el día", new { @type = "date" })
                @{var selectListLugar = new SelectList(new List<SelectListItem>
            {
            new SelectListItem { Text = "Aeropuerto", Value = "Aeropuerto"},
            new SelectListItem{ Text = "Terminal Buses", Value = "TerminalBuses"},
            new SelectListItem{ Text = "Hotel", Value = "Hotel"},
            }, "Value", "Text");
                }
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                <p>Retirar en: </p>
                @Html.DropDownList("LugarRetiro", selectListLugar, "Seleccione el lugar de retiro", new { @class = "form-control" })
            </div>
        </div>
               

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                <p>Devolver en: </p>

                @Html.DropDownList("LugarDevolucion", selectListLugar, "Seleccione el lugar de devolución", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-xs-12 col-md-5">
                <button type="submit" value="Guardar" class="btn btn-primary ">
                    <i class="fa fa-check"></i>  Guardar
                </button>

                @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-white" })
            </div>
        </div>


        
        
        </div>
    </div>

                
           }